In [27]:
import numpy as np
import pandas as pd
import urllib.request, urllib.parse, urllib.error
import requests
import json
import time
import os
URL1 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1"
URL1 = requests.get(URL1).json()
print (URL1)

{'page': 1, 'total_results': 6358, 'total_pages': 318, 'results': [{'popularity': 16.797, 'vote_count': 2101, 'video': False, 'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg', 'id': 19404, 'adult': False, 'backdrop_path': '/mMaxGuQKuH4WUHBwUNhJOetDYE9.jpg', 'original_language': 'hi', 'original_title': 'दिलवाले दुल्हनिया ले जायेंगे', 'genre_ids': [35, 18, 10749], 'title': 'Dilwale Dulhania Le Jayenge', 'vote_average': 8.9, 'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'release_date': '1995-10-20'}, {'popularity': 30.766, 'vote_count': 13676, 'video': False, 'poster_path': '/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg', 'id': 278, 'adult': False, 'backdrop_path': '/j9XKiZrVeViAixVRzCta7h1VU9W.jpg', 'original_language': 'en', 'original_title': 'The Shawshank Redemption', 'genre_ids': [80, 18], 'title': 'The Shawshank Redemption', 'vote_average': 8.7, 'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'release_date': '1994-09-23'}, {'popularity': 28.39, 'vote_count': 10457, 'video': False, 'poster_path': '/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg', 'id': 238, 'adult': False, 'backdrop_path': '/6xKCYgH16UuwEGAyroLU6p8HLIn.jpg', 'original_language': 'en', 'original_title': 'The Godfather', 'genre_ids': [80, 18], 'title': 'The Godfather', 'vote_average': 8.6, 'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'release_date': '1972-03-15'}, {'popularity': 42.412, 'vote_count': 558, 'video': False, 'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'id': 496243, 'adult': False, 'backdrop_path': '/cM0pnzCF6T7u1AAEYgyCG6Sua6k.jpg', 'original_language': 'ko', 'original_title': '기생충', 'genre_ids': [35, 18, 53], 'title': 'Parasite', 'vote_average': 8.6, 'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", 'release_date': '2019-10-11'}, {'popularity': 25.374, 'vote_count': 4444, 'video': False, 'poster_path': '/xq1Ugd62d23K2knRUx6xxuALTZB.jpg', 'id': 372058, 'adult': False, 'backdrop_path': '/nvsdKYPKwf51EAgC0xLJMB9kUZM.jpg', 'original_language': 'ja', 'original_title': '君の名は。', 'genre_ids': [16, 18, 10749], 'title': 'Your Name.', 'vote_average': 8.6, 'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'release_date': '2017-04-07'}, {'popularity': 24.831, 'vote_count': 8399, 'video': False, 'poster_path': '/yPisjyLweCl1tbgwgtzBCNCBle.jpg', 'id': 424, 'adult': False, 'backdrop_path': '/cTNYRUTXkBgPH3wP3kmPUB5U6dA.jpg', 'original_language': 'en', 'original_title': "Schindler's List", 'genre_ids': [18, 36, 10752], 'title': "Schindler's List", 'vote_average': 8.5, 'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'release_date': '1993-12-15'}, {'popularity': 25.065, 'vote_count': 6149, 'video': False, 'poster_path': '/bVq65huQ8vHDd1a4Z37QtuyEvpA.jpg', 'id': 240, 'adult': False, 'backdrop_path': '/gLbBRyS7MBrmVUNce91Hmx9vzqI.jpg', 'original_language': 'en', 'original_title': 'The Godfather: Part II', 'genre_ids': [80, 18], 'title': 'The Godfather: Part II', 'vote_average': 8.5, 'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'release_date': '1974-12-20'}, {'popularity': 28.033, 'vote_count': 7751, 'video': False, 'poster_path': '/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg', 'id': 129, 'adult': False, 'backdrop_path': '/mnpRKVSXBX6jb56nabvmGKA0Wig.jpg', 'original_language': 'ja', 'original_title': '千と千尋の神隠し', 'genre_ids': [16, 14, 10751], 'title': 'Spirited Away', 'vote_average': 8.5, 'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'release_date': '2002-09-20'}, {'popularity': 18.739, 'id': 497, 'video': False, 'vote_count': 8672, 'vote_average': 8.5, 'title': 'The Green Mile', 'release_date': '1999-12-10', 'original_language': 'en', 'original_title': 'The Green Mile', 'genre_ids': [14, 18, 80], 'backdrop_path': '/Rlt20sEbOQKPVjia7lUilFm49W.jpg', 'adult': False, 'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.", 'poster_path': '/sOHqdY1RnSn6kcfAHKu28jvTebE.jpg'}, {'popularity': 17.761, 'vote_count': 7540, 'video': False, 'poster_path': '/f7DImXDebOs148U4uPjI61iDvaK.jpg', 'id': 637, 'adult': False, 'backdrop_path': '/bORe0eI72D874TMawOOFvqWS6Xe.jpg', 'original_language': 'it', 'original_title': 'La vita è bella', 'genre_ids': [35, 18], 'title': 'Life Is Beautiful', 'vote_average': 8.5, 'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.', 'release_date': '1998-10-22'}, {'popularity': 32.587, 'vote_count': 15909, 'video': False, 'poster_path': '/dM2w364MScsjFf8pfMbaWUcWrR.jpg', 'id': 680, 'adult': False, 'backdrop_path': '/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg', 'original_language': 'en', 'original_title': 'Pulp Fiction', 'genre_ids': [80, 53], 'title': 'Pulp Fiction', 'vote_average': 8.4, 'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.", 'release_date': '1994-10-14'}, {'popularity': 44.072, 'vote_count': 4884, 'video': False, 'poster_path': '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', 'id': 324857, 'adult': False, 'backdrop_path': '/uUiId6cG32JSRI6RyBQSvQtLjz2.jpg', 'original_language': 'en', 'original_title': 'Spider-Man: Into the Spider-Verse', 'genre_ids': [28, 12, 16, 35, 878], 'title': 'Spider-Man: Into the Spider-Verse', 'vote_average': 8.4, 'overview': 'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.', 'release_date': '2018-12-14'}, {'popularity': 39.583, 'vote_count': 19498, 'video': False, 'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'id': 155, 'adult': False, 'backdrop_path': '/hqkIcbrOHL86UncnHIsHVcVmzue.jpg', 'original_language': 'en', 'original_title': 'The Dark Knight', 'genre_ids': [28, 80, 18, 53], 'title': 'The Dark Knight', 'vote_average': 8.4, 'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'release_date': '2008-07-18'}, {'popularity': 22.885, 'vote_count': 15522, 'video': False, 'poster_path': '/yE5d3BUhE8hCnkMUJOo1QDoOGNz.jpg', 'id': 13, 'adult': False, 'backdrop_path': '/wMgbnUVS9wbRGAdki8fqxKU1O0N.jpg', 'original_language': 'en', 'original_title': 'Forrest Gump', 'genre_ids': [35, 18, 10749], 'title': 'Forrest Gump', 'vote_average': 8.4, 'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'release_date': '1994-07-06'}, {'popularity': 31.33, 'vote_count': 16894, 'video': False, 'poster_path': '/adw6Lq9FiC9zjYEpOqfq03ituwp.jpg', 'id': 550, 'adult': False, 'backdrop_path': '/mMZRKb3NVo5ZeSPEIaNW9buLWQ0.jpg', 'original_language': 'en', 'original_title': 'Fight Club', 'genre_ids': [18], 'title': 'Fight Club', 'vote_average': 8.4, 'overview': 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.', 'release_date': '1999-10-15'}, {'popularity': 42.83, 'id': 122, 'video': False, 'vote_count': 13667, 'vote_average': 8.4, 'title': 'The Lord of the Rings: The Return of the King', 'release_date': '2003-12-17', 'original_language': 'en', 'original_title': 'The Lord of the Rings: The Return of the King', 'genre_ids': [12, 14, 28], 'backdrop_path': '/8BPZO0Bf8TeAy8znF43z8soK3ys.jpg', 'adult': False, 'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam bring the ring closer to the heart of Mordor, the dark lord's realm.", 'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg'}, {'popularity': 18.024, 'vote_count': 5195, 'video': False, 'poster_path': '/81d8oyEFgj7FlxJqSDXWr8JH8kV.jpg', 'id': 539, 'adult': False, 'backdrop_path': '/3md49VBCeqY6MSNyAVY6d5eC6bA.jpg', 'original_language': 'en', 'original_title': 'Psycho', 'genre_ids': [18, 27, 53], 'title': 'Psycho', 'vote_average': 8.4, 'overview': 'When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother. The place seems quirky, but fine… until Marion decides to take a shower.', 'release_date': '1960-09-08'}, {'popularity': 9.953, 'vote_count': 270, 'video': False, 'poster_path': '/5konZnIbcAxZjP616Cz5o9bKEfW.jpg', 'id': 14537, 'adult': False, 'backdrop_path': '/pz9fxHyGiiNLZ21bccAtwrMAH7f.jpg', 'original_language': 'ja', 'original_title': '切腹', 'genre_ids': [28, 18, 36], 'title': 'Harakiri', 'vote_average': 8.4, 'overview': 'Aging samurai Hanshiro Tsugumo arrives at the home of Kageyu Saito and asks to commit a ritual suicide on the property, which Saito thinks is a ploy to gain pity and a job. Saito tells Tsugumo of another samurai, Motome Chijiiwa, who threatened suicide as a stratagem, only to be forced to follow through on the task. When Tsugumo reveals that Chijiiwa was his son-in-law, the disclosure sets off a fierce conflict.', 'release_date': '1963-09-11'}, {'popularity': 20.671, 'vote_count': 4220, 'video': False, 'poster_path': '/wfPHdfofBD5PN96dV96a51B3Ja2.jpg', 'id': 429, 'adult': False, 'backdrop_path': '/xGC2fY5KFmtuXnsuQwYQKFOLZFy.jpg', 'original_language': 'it', 'original_title': 'Il buono, il brutto, il cattivo', 'genre_ids': [37], 'title': 'The Good, the Bad and the Ugly', 'vote_average': 8.4, 'overview': 'While the Civil War rages between the Union and the Confederacy, three men – a quiet loner, a ruthless hit man and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'release_date': '1967-12-29'}, {'popularity': 14.273, 'id': 389, 'video': False, 'vote_count': 3922, 'vote_average': 8.4, 'title': '12 Angry Men', 'release_date': '1957-04-10', 'original_language': 'en', 'original_title': '12 Angry Men', 'genre_ids': [18], 'backdrop_path': '/lH2Ga8OzjU1XlxJ73shOlPx6cRw.jpg', 'adult': False, 'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", 'poster_path': '/3W0v956XxSG5xgm7LB6qu8ExYJ2.jpg'}]}

In [28]:
URL1.keys()

dict_keys(['page', 'total_results', 'total_pages', 'results'])

In [29]:
DF1 = pd.DataFrame(URL1['results'])

In [30]:
DF1.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/mMaxGuQKuH4WUHBwUNhJOetDYE9.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",16.797,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.9,2101
1,False,/j9XKiZrVeViAixVRzCta7h1VU9W.jpg,"[80, 18]",278,en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,30.766,/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg,1994-09-23,The Shawshank Redemption,False,8.7,13676
2,False,/6xKCYgH16UuwEGAyroLU6p8HLIn.jpg,"[80, 18]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",28.390,/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg,1972-03-15,The Godfather,False,8.6,10457
3,False,/cM0pnzCF6T7u1AAEYgyCG6Sua6k.jpg,"[35, 18, 53]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",42.412,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-10-11,Parasite,False,8.6,558
4,False,/nvsdKYPKwf51EAgC0xLJMB9kUZM.jpg,"[16, 18, 10749]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,25.374,/xq1Ugd62d23K2knRUx6xxuALTZB.jpg,2017-04-07,Your Name.,False,8.6,4444

In [31]:
DF1.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [32]:
DF1.head()

,id,overview,popularity,release_date,title,vote_average
0,19404,"Raj is a rich, carefree, happy-go-lucky second...",16.797,1995-10-20,Dilwale Dulhania Le Jayenge,8.9
1,278,Framed in the 1940s for the double murder of h...,30.766,1994-09-23,The Shawshank Redemption,8.7
2,238,"Spanning the years 1945 to 1955, a chronicle o...",28.390,1972-03-15,The Godfather,8.6
3,496243,"All unemployed, Ki-taek's family takes peculia...",42.412,2019-10-11,Parasite,8.6
4,372058,High schoolers Mitsuha and Taki are complete s...,25.374,2017-04-07,Your Name.,8.6

In [33]:
URL2 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=2"
URL2 = requests.get(URL2).json()
DF2 = pd.DataFrame(URL2['results'])
DF2.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [34]:
DF2.head()

,id,overview,popularity,release_date,title,vote_average
0,769,"The true story of Henry Hill, a half-Irish, ha...",22.090,1990-09-19,GoodFellas,8.4
1,311,A former Prohibition-era Jewish gangster retur...,15.278,1984-06-01,Once Upon a Time in America,8.4
2,11216,"A filmmaker recalls his childhood, when he fel...",10.145,2002-06-14,Cinema Paradiso,8.4
3,346,A samurai answers a village's request for prot...,13.477,1956-11-19,Seven Samurai,8.4
4,510,While serving time for insanity at a state men...,19.960,1975-11-18,One Flew Over the Cuckoo's Nest,8.4

In [35]:
URL3 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=3"
URL3 = requests.get(URL3).json()
DF3 = pd.DataFrame(URL3['results'])
DF3.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [36]:
URL4 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=4"
URL4 = requests.get(URL4).json()
DF4 = pd.DataFrame(URL4['results'])
DF4.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [37]:
URL5 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=5"
URL5 = requests.get(URL5).json()
DF5 = pd.DataFrame(URL5['results'])
DF5.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [38]:
URL6 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=6"
URL6 = requests.get(URL6).json()
DF6 = pd.DataFrame(URL6['results'])
DF6.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [39]:
URL7 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=7"
URL7 = requests.get(URL7).json()
DF7 = pd.DataFrame(URL7['results'])
DF7.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [40]:
URL8 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=8"
URL8 = requests.get(URL8).json()
DF8 = pd.DataFrame(URL8['results'])
DF8.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [41]:
URL9 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=9"
URL9 = requests.get(URL9).json()
DF9 = pd.DataFrame(URL9['results'])
DF9.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [42]:
URL10 = "https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=10"
URL10 = requests.get(URL10).json()
DF10 = pd.DataFrame(URL10['results'])
DF10.drop(['adult', 'backdrop_path', 'genre_ids', 'original_language', 'poster_path', 'original_title', 'video', 'vote_count'], axis=1, inplace=True)

In [43]:
DF=pd.concat([DF1, DF2, DF3, DF4, DF5, DF6, DF7, DF8, DF9, DF10])

In [44]:
DF.head()

,id,overview,popularity,release_date,title,vote_average
0,19404,"Raj is a rich, carefree, happy-go-lucky second...",16.797,1995-10-20,Dilwale Dulhania Le Jayenge,8.9
1,278,Framed in the 1940s for the double murder of h...,30.766,1994-09-23,The Shawshank Redemption,8.7
2,238,"Spanning the years 1945 to 1955, a chronicle o...",28.390,1972-03-15,The Godfather,8.6
3,496243,"All unemployed, Ki-taek's family takes peculia...",42.412,2019-10-11,Parasite,8.6
4,372058,High schoolers Mitsuha and Taki are complete s...,25.374,2017-04-07,Your Name.,8.6

In [45]:
DF.info

<bound method DataFrame.info of         id                                           overview  popularity  \
0    19404  Raj is a rich, carefree, happy-go-lucky second...      16.797
1      278  Framed in the 1940s for the double murder of h...      30.766
2      238  Spanning the years 1945 to 1955, a chronicle o...      28.390
3   496243  All unemployed, Ki-taek's family takes peculia...      42.412
4   372058  High schoolers Mitsuha and Taki are complete s...      25.374
5      424  The true story of how businessman Oskar Schind...      24.831
6      240  In the continuing saga of the Corleone crime f...      25.065
7      129  A young girl, Chihiro, becomes trapped in a st...      28.033
8      497  A supernatural tale set on death row in a Sout...      18.739
9      637  A touching story of an Italian book seller of ...      17.761
10     680  A burger-loving hit man, his philosophical par...      32.587
11  324857  Miles Morales is juggling his life between bei...      44.072
12     155  Batman raises the stakes in his war on crime. ...      39.583
13      13  A man with a low IQ has accomplished great thi...      22.885
14     550  A ticking-time-bomb insomniac and a slippery s...      31.330
15     122  Aragorn is revealed as the heir to the ancient...      42.830
16     539  When larcenous real estate clerk Marion Crane ...      18.024
17   14537  Aging samurai Hanshiro Tsugumo arrives at the ...       9.953
18     429  While the Civil War rages between the Union an...      20.671
19     389  The defense and the prosecution have rested an...      14.273
0      769  The true story of Henry Hill, a half-Irish, ha...      22.090
1      311  A former Prohibition-era Jewish gangster retur...      15.278
2    11216  A filmmaker recalls his childhood, when he fel...      10.145
3      346  A samurai answers a village's request for prot...      13.477
4      510  While serving time for insanity at a state men...      19.960
5    40096  The lively João Grilo and the sly Chicó are po...       7.994
6      901  City Lights is the first silent film that Char...      10.318
7   244786  Under the direction of a ruthless instructor, ...      21.054
8    12477  In the final months of World War II, 14-year-o...       0.600
9      598  Cidade de Deus is a shantytown that started du...      13.088
..     ...                                                ...         ...
10    1092  In postwar Vienna, Austria, Holly Martins, a w...      10.908
11     348  During its return to the earth, commercial spa...      22.691
12      38  Joel Barish, heartbroken that his girlfriend u...      13.133
13      15  Newspaper magnate, Charles Foster Kane is take...      13.857
14   19426  Rome, 1957. A woman, Cabiria, is robbed and le...       7.800
15    1059  Japanese peasants Matashichi and Tahei try and...       8.484
16    1955  A Victorian surgeon rescues a heavily disfigur...      10.278
17  310569  After leaving her daughter Jessica in a small ...       7.569
18  140420  An urban office worker finds that paper airpla...       7.235
19   18438  Mr. Kim is jobless, lost in debt and has been ...       6.356
0      387  A German submarine hunts allied ships during t...      11.567
1   424694  Singer Freddie Mercury, guitarist Brian May, d...      33.563
2      204  In the South American jungle, supplies of nitr...       9.313
3    32085  Young Vincent Malloy dreams of being just like...       6.467
4      821  In 1947, four German judges who served on the ...       7.799
5   103663  A teacher lives a lonely life, all the while s...      10.807
6     7347  In 1997, before the visit of the pope to Rio d...       9.089
7       62  Humanity finds a mysterious object buried bene...      20.823
8      110  Part-time model Valentine meets a retired judg...       8.465
9      521  An ex-tennis pro carries out a plot to have hi...      18.882
10   37165  Truman Burbank is the star of "The Truman Show...      19.609
11  120467  The Grand Budapest Hotel tells of a legendary ...      15.666
12     595  Scout Finch, 6, and her older brother Jem live...       8.359
13   68718  With the help of a German bounty hunter, a fre...      30.913
14   38286  Three friends - Aldo, Giovanni, and Giacomo - ...       7.732
15   28971  A fading music hall comedian tries to help a d...       6.190
16      14  Lester Burnham, a depressed suburban father in...      21.172
17     641  The hopes and dreams of four ambitious people ...       5.210
18     406  Aimlessly whiling away their days in the concr...       9.296
19    3083  Naive and idealistic Jefferson Smith, leader o...      11.401

   release_date                                          title  vote_average
0    1995-10-20                    Dilwale Dulhania Le Jayenge           8.9
1    1994-09-23                       The Shawshank Redemption           8.7
2    1972-03-15                                  The Godfather           8.6
3    2019-10-11                                       Parasite           8.6
4    2017-04-07                                     Your Name.           8.6
5    1993-12-15                               Schindler's List           8.5
6    1974-12-20                         The Godfather: Part II           8.5
7    2002-09-20                                  Spirited Away           8.5
8    1999-12-10                                 The Green Mile           8.5
9    1998-10-22                              Life Is Beautiful           8.5
10   1994-10-14                                   Pulp Fiction           8.4
11   2018-12-14              Spider-Man: Into the Spider-Verse           8.4
12   2008-07-18                                The Dark Knight           8.4
13   1994-07-06                                   Forrest Gump           8.4
14   1999-10-15                                     Fight Club           8.4
15   2003-12-17  The Lord of the Rings: The Return of the King           8.4
16   1960-09-08                                         Psycho           8.4
17   1963-09-11                                       Harakiri           8.4
18   1967-12-29                 The Good, the Bad and the Ugly           8.4
19   1957-04-10                                   12 Angry Men           8.4
0    1990-09-19                                     GoodFellas           8.4
1    1984-06-01                    Once Upon a Time in America           8.4
2    2002-06-14                                Cinema Paradiso           8.4
3    1956-11-19                                  Seven Samurai           8.4
4    1975-11-18                One Flew Over the Cuckoo's Nest           8.4
5    2000-09-15                                   A Dog's Will           8.4
6    1931-03-07                                    City Lights           8.4
7    2014-10-10                                       Whiplash           8.4
8    2019-01-01                         Grave of the Fireflies           8.4
9    2002-08-31                                    City of God           8.4
..          ...                                            ...           ...
10   1950-02-02                                  The Third Man           8.1
11   1979-05-25                                          Alien           8.1
12   2004-03-19          Eternal Sunshine of the Spotless Mind           8.1
13   1941-05-01                                   Citizen Kane           8.1
14   1957-12-31                              Nights of Cabiria           8.1
15   1958-12-28                            The Hidden Fortress           8.1
16   1980-10-03                               The Elephant Man           8.1
17   2015-08-28                              The Second Mother           8.1
18   2012-11-02                                       Paperman           8.1
19   2010-02-05                           Castaway on the Moon           8.1
0    1982-02-10                                       Das Boot           8.1
1    2018-11-02                              Bohemian Rhapsody           8.1
2    1955-02-16                              The Wages of Fear           8.1
3    1982-01-01                                        Vincent           8.1
4    1961-12-19                          Judgment at Nuremberg           8.1
5    2013-07-12                                       The Hunt           8.0
6    2008-09-19                                    Elite Squad           8.0
7    1968-04-10                          2001: A Space Odyssey           8.0
8    1994-11-23                              Three Colors: Red           8.0
9    1954-05-29                              Dial M for Murder           8.0
10   1998-06-05                                The Truman Show           8.0
11   2014-03-07                       The Grand Budapest Hotel           8.0
12   1962-12-25                          To Kill a Mockingbird           8.0
13   2012-12-25                               Django Unchained           8.0
14   1997-12-27                         Tre Uomini e una Gamba           8.0
15   1952-10-31                                      Limelight           8.0
16   1999-09-15                                American Beauty           8.0
17   2000-10-06                            Requiem for a Dream           8.0
18   1996-02-09                                       La Haine           8.0
19   1939-10-19                   Mr. Smith Goes to Washington           8.0

[200 rows x 6 columns]>